export const PRODUCTS = [
  {
    id: 1,
    title: "ساعت هوشمند اپل سری 6",
    category: "smartwatch",
    categoryLabel: "ساعت هوشمند",
    brand: "Apple",
    slug: "apple-watch-series-6",
    price: 48250000,
    src: "/images/Cart/AppleWatch.png",
  },
  {
    id: 2,
    title: "ایرپاد پرو ۲",
    category: "accessory",
    categoryLabel: "لوازم جانبی",
    brand: "Apple",
    slug: "airpods-pro-2",
    price: 16500000,
    src: "/images/Cart/airpodspro2.png",
  },
  {
    id: 3,
    title: "گوشی سامسونگ S23",
    category: "phone",
    categoryLabel: "گوشی موبایل",
    brand: "Samsung",
    slug: "samsung-galaxy-s23",
    price: 39800000,
    src: "/images/Cart/S23.png",
  },
  {
    id: 4,
    title: "لپ‌تاپ دل XPS 13",
    category: "laptop",
    categoryLabel: "لپ‌تاپ",
    brand: "Dell",
    slug: "dell-xps-13",
    price: 62400000,
    src: "/images/Cart/AppleWatch.png",
  },
  {
    id: 5,
    title: "هدفون بلوتوثی شیائومی مدل Redmi Buds 5",
    category: "accessory",
    categoryLabel: "لوازم جانبی",
    brand: "Xiaomi",
    slug: "xiaomi-redmi-buds-5",
    price: 2950000,
    src: "/images/Cart/RedmiBuds.png",
  },
  {
    id: 6,
    title: "مانیتور ال‌جی 27 اینچ",
    category: "monitor",
    categoryLabel: "مانیتور",
    brand: "LG",
    slug: "lg-monitor-27-inch",
    price: 18700000,
    src: "/images/Cart/AppleWatch.png",
  },
  {
    id: 7,
    title: "تبلت آیپد پرو ۱۲.۹ اینچ",
    category: "tablet",
    categoryLabel: "تبلت",
    brand: "Apple",
    slug: "ipad-pro-12-9",
    price: 75000000,
    src: "/images/Cart/AppleWatch.png",
  },
  {
    id: 8,
    title: "هدفون سونی WH-1000XM4",
    category: "accessory",
    categoryLabel: "لوازم جانبی",
    brand: "Sony",
    slug: "sony-wh-1000xm4",
    price: 21500000,
    src: "/images/Cart/AppleWatch.png",
  },
  {
    id: 9,
    title: "گوشی شیائومی Mi 11",
    category: "phone",
    categoryLabel: "گوشی موبایل",
    brand: "Xiaomi",
    slug: "xiaomi-mi-11",
    price: 27300000,
    src: "/images/Cart/AppleWatch.png",
  },
  {
    id: 10,
    title: "لپ‌تاپ اپل مک‌بوک پرو 13",
    category: "laptop",
    categoryLabel: "لپ‌تاپ",
    brand: "Apple",
    slug: "apple-macbook-pro-13",
    price: 85000000,
    src: "/images/Cart/AppleWatch.png",
  },
];

export const CATEGORIES = [
  {
    id: 1,
    name: "گوشی موبایل",
    alt: "phone",
    path: "/images/categories/phone.svg",
    key: "phone",
  },
  {
    id: 2,
    name: "لپ‌تاپ",
    alt: "laptop",
    path: "/images/categories/laptop.svg",
    key: "laptop",
  },
  {
    id: 3,
    name: "ساعت هوشمند",
    alt: "smartwatch",
    path: "/images/categories/watch.svg",
    key: "smartwatch",
  },
  {
    id: 4,
    name: "لوازم جانبی",
    alt: "accessory",
    path: "/images/categories/accessory.svg",
    key: "accessory",
  },
  {
    id: 5,
    name: "مانیتور",
    alt: "monitor",
    path: "/images/categories/monitor.svg",
    key: "monitor",
  },
  {
    id: 6,
    name: "تبلت",
    alt: "tablet",
    path: "/images/categories/tablet.svg",
    key: "tablet",
  },
  {
    id: 7,
    name: "تلویزیون",
    alt: "tv",
    path: "/images/categories/tv.svg",
    key: "tv",
  },
  {
    id: 8,
    name: "کنسول بازی",
    alt: "console",
    path: "/images/categories/console.svg",
    key: "console",
  },
  {
    id: 9,
    name: "دوربین",
    alt: "camera",
    path: "/images/categories/camera.svg",
    key: "camera",
  },
];

export const FILTERS = [
  {
    id: 1,
    name: "برند محصول",
    icon: "/images/categories/brand.svg",
    alt: "brand",
    href: "/",
  },
  {
    id: 2,
    name: "رنگ محصول",
    icon: "/images/categories/color.svg",
    alt: "color",
    href: "/",
  },
  {
    id: 3,
    name: "محدوده قیمت",
    icon: "/images/categories/price.svg",
    alt: "price",
    href: "/",
  },
];

export const SORT_OPTIONS = [
  { key: "popular", label: "محبوب ترین محصول" },
  { key: "visited", label: "پر بازدید ترین محصول" },
  { key: "expensive", label: "گران ترین محصول" },
  { key: "cheap", label: "ارزان ترین محصول" },
];
