import "./globals.css";

export const metadata = {
  title: "DigiTize App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="bg-brand-stone-100 px-4">{children}</body>
    </html>
  );
}
